### PR TITLE
flake8Changes

### PR DESCRIPTION
**Pull request by OSHistory**
Did some changes to apply pep8 style recommodations. Bigger changes 
in the structure of the code where avoided, so no line breaks or similar 
inserted. 
BTW: Great project, hope to commit in the feature

### CODE REVIEW

**Comment by mgiraldo** [comment]
sad thing that i don't have write access to this repo anymore or i would merge the changes
`¯\_(ツ)_/¯`

**Comment by OSHistory** [comment]
Ok, so there is no project administrator at the moment? 
The project website seems to be still active, though.

**Comment by mgiraldo** [comment]
maybe bring it up with @nonword

**Comment by jeffreyameyer** [comment]
@OSHistory - if you'd like to do further work, we'll be maintaining a more active repo over here: https://github.com/OpenHistoricalMap/map-vectorizer

**Comment by OSHistory** [comment]
@jeffreyameyer Thanks, I'll commit there

**Pull request closed without merging**
