### PR TITLE
update methods codes for opencv 3x

### PR DESCRIPTION
**Pull request by jsta**

### CODE REVIEW

**Comment by mgiraldo** [comment]
i get a `AttributeError: 'module' object has no attribute 'HOUGH_GRADIENT'` error in `detect.py` line 46 when using Python 2.7.10

**Comment by jsta** [comment]
It works for me. Are you using OpenCV 3? As far as I can tell, the text of the PR matches the current OpenCV docs as well as the tutorial at: http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_houghcircles/py_houghcircles.html

```
python --version
```

> Python 2.7.12

**Comment by mgiraldo** [comment]
tested with Python 2.7.13 and didn't work either. how do i make sure i have OpenCV 3? (not an expert on this)

also: how can we not make it a requirement to have OpenCV 3 while supporting those who have it?

**Comment by jsta** [comment]
```
pkg-config --modversion opencv
```

> 3.2.0

The easiest way I can think of is to create a repo branch specific to opencv v2. I found this transition guide describing v2 to v3 (http://docs.opencv.org/master/db/dfa/tutorial_transition_guide.html), but I don't see any easy answers there.

**Comment by mgiraldo** [comment]
added the `opencv-python` package and now no more opencv problems :)

thanks for the contribution!

**Pull request merged**
